package Utils;

public enum TestScenarioAdmin {
	
	T001("Admin valid login"),
	T002("Admin Select Absen from dashboard to masuk"),
	T003("Admin input form absen masuk position call center"),
	T004("Admin input form absen masuk position administrasi"),
	T005("Admin input form absen masuk position spg"),
	T006("Admin input form absen masuk position null"),
	T007("Admin input form absen masuk branch bandung"),
	T008("Admin input form absen masuk branch jakarta"),
	T009("Admin input form absen masuk branch surabaya"),
	T010("Admin input form absen masuk branch null"),
	T011("Admin input form absen masuk unit airasia"),
	T012("Admin input form absen masuk unit bca api"),
	T013("Admin input form absen masuk unit it programmer"),
	T014("Admin input form absen masuk unit null"),
	T015("Admin input form absen masuk start date lebih dari 1bulan dari end date"),
	T016("Admin input form absen masuk start date lebih tinggi dari end date"),
	T017("Admin input form absen masuk end date lebih dari 1bulan dari start date"),
	T018("Admin input form absen masuk end date lebih rendah dari start date"),
	T019("Admin input form absen masuk possition all"),
	T020("Admin input form absen masuk branch all"),
	T021("Admin input form absen masuk unit all"),
	T022("Admin input form absen masuk start date true"),
	T023("Admin input form absen masuk end date true"),
	T024("Admin Select Absen from dashboard to pulang"),
	T025("Admin input form absen pulang position call center"),
	T026("Admin input form absen pulang position administrasi"),
	T027("Admin input form absen pulang position spg"),
	T028("Admin input form absen pulang position null"),
	T029("Admin input form absen pulang branch bandung"),
	T030("Admin input form absen pulang branch jakarta"),
	T031("Admin input form absen pulang branch surabaya"),
	T032("Admin input form absen pulang branch null"),
	T033("Admin input form absen pulang unit airasia"),
	T034("Admin input form absen pulang unit bca api"),
	T035("Admin input form absen pulang unit it programmer"),
	T036("Admin input form absen pulang unit null"),
	T037("Admin input form absen pulang start date lebih dari 1bulan dari end date"),
	T038("Admin input form absen pulang start date lebih tinggi dari end date"),
	T039("Admin input form absen pulang end date lebih dari 1bulan dari start date"),
	T040("Admin input form absen pulang end date lebih rendah dari start date"),
	T041("Admin input form absen pulang possition all"),
	T042("Admin input form absen pulang branch all"),
	T043("Admin input form absen pulang unit all"),
	T044("Admin input form absen pulang start date true"),
	T045("Admin input form absen pulang end date true"),
	T046("Admin Select Absen from dashboard to sakit"),
	T047("Admin input form absen sakit position call center"),
	T048("Admin input form absen sakit position administrasi"),
	T049("Admin input form absen sakit position spg"),
	T050("Admin input form absen sakit position null"),
	T051("Admin input form absen sakit branch bandung"),
	T052("Admin input form absen sakit branch jakarta"),
	T053("Admin input form absen sakit branch surabaya"),
	T054("Admin input form absen sakit branch null"),
	T055("Admin input form absen sakit unit airasia"),
	T056("Admin input form absen sakit unit bca api"),
	T057("Admin input form absen sakit unit it programmer"),
	T058("Admin input form absen sakit unit null"),
	T059("Admin input form absen sakit start date lebih dari 1bulan dari end date"),
	T060("Admin input form absen sakit start date lebih tinggi dari end date"),
	T061("Admin input form absen sakit end date lebih dari 1bulan dari start date"),
	T062("Admin input form absen sakit end date lebih rendah dari start date"),
	T063("Admin input form absen sakit possition all"),
	T064("Admin input form absen sakit branch all"),
	T065("Admin input form absen sakit unit all"),
	T066("Admin input form absen sakit start date true"),
	T067("Admin input form absen sakit end date true"),
	T068("Admin Select Absen from dashboard to off"),
	T069("Admin input form absen off position call center"),
	T070("Admin input form absen off position administrasi"),
	T071("Admin input form absen off position spg"),
	T072("Admin input form absen off position null"),
	T073("Admin input form absen off branch bandung"),
	T074("Admin input form absen off branch jakarta"),
	T075("Admin input form absen off branch surabaya"),
	T076("Admin input form absen off branch null"),
	T077("Admin input form absen off unit airasia"),
	T078("Admin input form absen off unit bca api"),
	T079("Admin input form absen off unit it programmer"),
	T080("Admin input form absen off unit null"),
	T081("Admin input form absen off start date lebih dari 1bulan dari end date"),
	T082("Admin input form absen off start date lebih tinggi dari end date"),
	T083("Admin input form absen off end date lebih dari 1bulan dari start date"),
	T084("Admin input form absen off end date lebih rendah dari start date"),
	T085("Admin input form absen off possition all"),
	T086("Admin input form absen off branch all"),
	T087("Admin input form absen off unit all"),
	T088("Admin input form absen off start date true"),
	T089("Admin input form absen off end date true"),
	T090("Admin Select Absen from dashboard to shifting"),
	T091("Admin input form absen shifting position call center"),
	T092("Admin input form absen shifting position administrasi"),
	T093("Admin input form absen shifting position spg"),
	T094("Admin input form absen shifting position null"),
	T095("Admin input form absen shifting branch bandung"),
	T096("Admin input form absen shifting branch jakarta"),
	T097("Admin input form absen shifting branch surabaya"),
	T098("Admin input form absen shifting branch null"),
	T099("Admin input form absen shifting unit airasia"),
	T100("Admin input form absen shifting unit bca api"),
	T101("Admin input form absen shifting unit it programmer"),
	T102("Admin input form absen shifting unit null"),
	T103("Admin input form absen shifting start date lebih dari 1bulan dari end date"),
	T104("Admin input form absen shifting start date lebih tinggi dari end date"),
	T105("Admin input form absen shifting end date lebih dari 1bulan dari start date"),
	T106("Admin input form absen shifting end date lebih rendah dari start date"),
	T107("Admin input form absen shifting possition all"),
	T108("Admin input form absen shifting branch all"),
	T109("Admin input form absen shifting unit all"),
	T110("Admin input form absen shifting start date true"),
	T111("Admin input form absen shifting end date true"),
	T112("Admin Select Absen from dashboard to non shifting"),
	T113("Admin input form absen non shifting position call center"),
	T114("Admin input form absen non shifting position administrasi"),
	T115("Admin input form absen non shifting position spg"),
	T116("Admin input form absen non shifting position null"),
	T117("Admin input form absen non shifting branch bandung"),
	T118("Admin input form absen non shifting branch jakarta"),
	T119("Admin input form absen non shifting branch surabaya"),
	T120("Admin input form absen non shifting branch null"),
	T121("Admin input form absen non shifting unit airasia"),
	T122("Admin input form absen non shifting unit bca api"),
	T123("Admin input form absen non shifting unit it programmer"),
	T124("Admin input form absen non shifting unit null"),
	T125("Admin input form absen non shifting start date lebih dari 1bulan dari end date"),
	T127("Admin input form absen non shifting start date lebih tinggi dari end date"),
	T128("Admin input form absen non shifting end date lebih dari 1bulan dari start date"),
	T129("Admin input form absen non shifting end date lebih rendah dari start date"),
	T130("Admin input form absen non shifting possition all"),
	T131("Admin input form absen non shifting branch all"),
	T141("Admin input form absen non shifting unit all"),
	T142("Admin input form absen non shifting start date true"),
	T143("Admin input form absen non shifting end date true"),
	T144("Admin Checking file"),
	T145("Admin Logout");
	
	private String testTMS;
	
	TestScenarioAdmin(String value) {
		testTMS = value;
	}
	
	public String getTestTMSAdmin() {
		return testTMS;
	}
}
/* 
 --------------------AdminLogin----------------
T01("Admin invalid login"),
T02("Admin Login null username"),
T03("Admin Login null password"),
T04("Admin valid login"),
T05("Admin Logout"); 
 
------------------- AdminReportMasuk-----------------
T01("Admin valid login"),
T02("Admin Select Absen from dashboard"),
T03("Admin input form absen masuk position call center"),
T04("Admin input form absen masuk position administrasi"),
T05("Admin input form absen masuk position spg"),
T06("Admin input form absen masuk position null"),
T07("Admin input form absen masuk branch bandung"),
T08("Admin input form absen masuk branch jakarta"),
T09("Admin input form absen masuk branch surabaya"),
T10("Admin input form absen masuk branch null"),
T11("Admin input form absen masuk unit airasia"),
T12("Admin input form absen masuk unit bca api"),
T13("Admin input form absen masuk unit it programmer"),
T14("Admin input form absen masuk unit null"),
T15("Admin input form absen masuk start date lebih dari 1bulan dari end date"),
T16("Admin input form absen masuk start date lebih tinggi dari end date"),
T17("Admin input form absen masuk end date lebih dari 1bulan dari start date"),
T18("Admin input form absen masuk end date lebih rendah dari start date"),
T19("Admin input form absen masuk possition all"),
T20("Admin input form absen masuk branch all"),
T21("Admin input form absen masuk unit all"),
T22("Admin input form absen masuk start date true"),
T23("Admin input form absen masuk end date true"),
T24("Admin Checking file"),
T25("Admin Logout");

------------------Admin Report Pulang-------------------
T01("Admin valid login"),
T02("Admin Select Absen from dashboard"),
T03("Admin input form absen pulang position call center"),
T04("Admin input form absen pulang position administrasi"),
T05("Admin input form absen pulang position spg"),
T06("Admin input form absen pulang position null"),
T07("Admin input form absen pulang branch bandung"),
T08("Admin input form absen pulang branch jakarta"),
T09("Admin input form absen pulang branch surabaya"),
T10("Admin input form absen pulang branch null"),
T11("Admin input form absen pulang unit airasia"),
T12("Admin input form absen pulang unit bca api"),
T13("Admin input form absen pulang unit it programmer"),
T14("Admin input form absen pulang unit null"),
T15("Admin input form absen pulang start date lebih dari 1bulan dari end date"),
T16("Admin input form absen pulang start date lebih tinggi dari end date"),
T17("Admin input form absen pulang end date lebih dari 1bulan dari start date"),
T18("Admin input form absen pulang end date lebih rendah dari start date"),
T19("Admin input form absen pulang possition all"),
T20("Admin input form absen pulang branch all"),
T21("Admin input form absen pulang unit all"),
T22("Admin input form absen pulang start date true"),
T23("Admin input form absen pulang end date true"),
T24("Admin Checking file");
T25("Admin Logout");

----------------------Admin Report Sakit-----------------------
T01("Admin valid login"),
T02("Admin Select Absen from dashboard"),
T03("Admin input form absen sakit position call center"),
T04("Admin input form absen sakit position administrasi"),
T05("Admin input form absen sakit position spg"),
T06("Admin input form absen sakit position null"),
T07("Admin input form absen sakit branch bandung"),
T08("Admin input form absen sakit branch jakarta"),
T09("Admin input form absen sakit branch surabaya"),
T10("Admin input form absen sakit branch null"),
T11("Admin input form absen sakit unit airasia"),
T12("Admin input form absen sakit unit bca api"),
T13("Admin input form absen sakit unit it programmer"),
T14("Admin input form absen sakit unit null"),
T15("Admin input form absen sakit start date lebih dari 1bulan dari end date"),
T16("Admin input form absen sakit start date lebih tinggi dari end date"),
T17("Admin input form absen sakit end date lebih dari 1bulan dari start date"),
T18("Admin input form absen sakit end date lebih rendah dari start date"),
T19("Admin input form absen sakit possition all"),
T20("Admin input form absen sakit branch all"),
T21("Admin input form absen sakit unit all"),
T22("Admin input form absen sakit start date true"),
T23("Admin input form absen sakit end date true"),
T24("Admin Checking file"),
T25("Admin Logout");

---------------------Admin Report Off---------------------------
T01("Admin valid login"),
T02("Admin Select Absen from dashboard"),
T03("Admin input form absen off position call center"),
T04("Admin input form absen off position administrasi"),
T05("Admin input form absen off position spg"),
T06("Admin input form absen off position null"),
T07("Admin input form absen off branch bandung"),
T08("Admin input form absen off branch jakarta"),
T09("Admin input form absen off branch surabaya"),
T10("Admin input form absen off branch null"),
T11("Admin input form absen off unit airasia"),
T12("Admin input form absen off unit bca api"),
T13("Admin input form absen off unit it programmer"),
T14("Admin input form absen off unit null"),
T15("Admin input form absen off start date lebih dari 1bulan dari end date"),
T16("Admin input form absen off start date lebih tinggi dari end date"),
T17("Admin input form absen off end date lebih dari 1bulan dari start date"),
T18("Admin input form absen off end date lebih rendah dari start date"),
T19("Admin input form absen off possition all"),
T20("Admin input form absen off branch all"),
T21("Admin input form absen off unit all"),
T22("Admin input form absen off start date true"),
T23("Admin input form absen off end date true"),
T24("Admin Checking file");
T25("Admin Logout");

------------------------Admin Report Shifting---------------------
T01("Admin valid login"),
T02("Admin Select Absen from dashboard"),
T03("Admin input form absen shifting position call center"),
T04("Admin input form absen shifting position administrasi"),
T05("Admin input form absen shifting position spg"),
T06("Admin input form absen shifting position null"),
T07("Admin input form absen shifting branch bandung"),
T08("Admin input form absen shifting branch jakarta"),
T09("Admin input form absen shifting branch surabaya"),
T10("Admin input form absen shifting branch null"),
T11("Admin input form absen shifting unit airasia"),
T12("Admin input form absen shifting unit bca api"),
T13("Admin input form absen shifting unit it programmer"),
T14("Admin input form absen shifting unit null"),
T15("Admin input form absen shifting start date lebih dari 1bulan dari end date"),
T16("Admin input form absen shifting start date lebih tinggi dari end date"),
T17("Admin input form absen shifting end date lebih dari 1bulan dari start date"),
T18("Admin input form absen shifting end date lebih rendah dari start date"),
T19("Admin input form absen shifting possition all"),
T20("Admin input form absen shifting branch all"),
T21("Admin input form absen shifting unit all"),
T22("Admin input form absen shifting start date true"),
T23("Admin input form absen shifting end date true"),
T24("Admin Checking file");
T25("Admin Logout");

------------------------Admin Report Non Shifting---------------------
T01("Admin valid login"),
T02("Admin Select Absen from dashboard"),
T03("Admin input form absen non shifting position call center"),
T04("Admin input form absen non shifting position administrasi"),
T05("Admin input form absen non shifting position spg"),
T06("Admin input form absen non shifting position null"),
T07("Admin input form absen non shifting branch bandung"),
T08("Admin input form absen non shifting branch jakarta"),
T09("Admin input form absen non shifting branch surabaya"),
T10("Admin input form absen non shifting branch null"),
T11("Admin input form absen non shifting unit airasia"),
T12("Admin input form absen non shifting unit bca api"),
T13("Admin input form absen non shifting unit it programmer"),
T14("Admin input form absen non shifting unit null"),
T15("Admin input form absen non shifting start date lebih dari 1bulan dari end date"),
T16("Admin input form absen non shifting start date lebih tinggi dari end date"),
T17("Admin input form absen non shifting end date lebih dari 1bulan dari start date"),
T18("Admin input form absen non shifting end date lebih rendah dari start date"),
T19("Admin input form absen non shifting possition all"),
T20("Admin input form absen non shifting branch all"),
T21("Admin input form absen non shifting unit all"),
T22("Admin input form absen non shifting start date true"),
T23("Admin input form absen non shifting end date true"),
T24("Admin Checking file"),
T25("Admin Logout");
*/
